// <auto-generated />
using System;
using Magic_Villa_VillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magic_Villa_VillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231026185443_addedDefaultVillaNumbers")]
    partial class addedDefaultVillaNumbers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1048),
                            Details = "Some default details",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1101),
                            Details = "Some default diamond villa details",
                            ImageUrl = "",
                            Name = "Diamond Villa",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 650,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1105),
                            Details = "Some default ukrainian villa details",
                            ImageUrl = "",
                            Name = "Ukrainian Villa",
                            Occupancy = 7,
                            Rate = 400.0,
                            Sqft = 750,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VillaNo");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 100,
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1268),
                            SpecialDetails = "Villa number is 100",
                            UpdatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1272)
                        },
                        new
                        {
                            VillaNo = 101,
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1274),
                            SpecialDetails = "Villa number is 101",
                            UpdatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1276)
                        },
                        new
                        {
                            VillaNo = 102,
                            CreatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1279),
                            SpecialDetails = "Villa number is 102",
                            UpdatedDate = new DateTime(2023, 10, 26, 21, 54, 42, 936, DateTimeKind.Local).AddTicks(1281)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
