// <auto-generated />
using System;
using Magic_Villa_VillaApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magic_Villa_VillaApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231123115147_addedLocalUsersToDb")]
    partial class addedLocalUsersToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.LocalUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(826),
                            Details = "Some default details",
                            ImageUrl = "",
                            Name = "Royal Villa",
                            Occupancy = 5,
                            Rate = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(878),
                            Details = "Some default diamond villa details",
                            ImageUrl = "",
                            Name = "Diamond Villa",
                            Occupancy = 6,
                            Rate = 300.0,
                            Sqft = 650,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amenity = "",
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(881),
                            Details = "Some default ukrainian villa details",
                            ImageUrl = "",
                            Name = "Ukrainian Villa",
                            Occupancy = 7,
                            Rate = 400.0,
                            Sqft = 750,
                            UpdateDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.VillaNumber", b =>
                {
                    b.Property<int>("VillaNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SpecialDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VillaId")
                        .HasColumnType("int");

                    b.HasKey("VillaNo");

                    b.HasIndex("VillaId");

                    b.ToTable("VillaNumbers");

                    b.HasData(
                        new
                        {
                            VillaNo = 100,
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1047),
                            SpecialDetails = "Villa number is 100",
                            UpdatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1050),
                            VillaId = 0
                        },
                        new
                        {
                            VillaNo = 101,
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1052),
                            SpecialDetails = "Villa number is 101",
                            UpdatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1054),
                            VillaId = 0
                        },
                        new
                        {
                            VillaNo = 102,
                            CreatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1056),
                            SpecialDetails = "Villa number is 102",
                            UpdatedDate = new DateTime(2023, 11, 23, 13, 51, 47, 687, DateTimeKind.Local).AddTicks(1058),
                            VillaId = 0
                        });
                });

            modelBuilder.Entity("Magic_Villa_VillaApi.Models.VillaNumber", b =>
                {
                    b.HasOne("Magic_Villa_VillaApi.Models.Villa", "Villa")
                        .WithMany()
                        .HasForeignKey("VillaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Villa");
                });
#pragma warning restore 612, 618
        }
    }
}
